name: 'Check YAML consistency'
on:
  workflow_call:
    inputs:
      file_name:
        description: 'The name of the file to check consistency for without extension'
        type: 'string'
jobs:
  check_yaml_consistency:
    name: 'Check YAML consistency'
    runs-on: 'ubuntu-latest'
    steps:
    - id: 'step-0'
      name: 'Check out'
      uses: 'actions/checkout@v4'
    - id: 'step-1'
      name: 'Execute script'
      run: 'rm ''.github/workflows/${{ inputs.file_name }}.yaml'' && ''.github/workflows/${{ inputs.file_name }}.main.kts'''
    - id: 'step-2'
      name: 'Consistency check'
      run: 'git diff --exit-code ''.github/workflows/${{ inputs.file_name }}.yaml'''